// -----------------------------------------------------------------------------
// This file was automatically generated.
// Please do not edit this file manually.
//
// Generated Date: 
//
// -----------------------------------------------------------------------------

using iSoft.Common.Utils;
using Microsoft.AspNetCore.Http;
using SourceBaseBE.Database.Entities;
using static iSoft.Common.ConstCommon;
using iSoft.Common;
using iSoft.Database.Models.RequestModels.Base.BaseCRUD;
using SourceBaseBE.Database.Enums;
using iSoft.Common.Enums;

namespace SourceBaseBE.Database.Models.RequestModels
{
    public class BaseTagRequestModel : BaseCRUDRequestModel<TagEntity>
    {
        public virtual string SerialCode { get; set; }
        public virtual string Name { get; set; }
        public virtual string? Type { get; set; }
        public virtual double? Offset { get; set; }
        public virtual long? DataBlockId { get; set; }
        public virtual List<long>? ListDataBlock { get; set; }
        
        public override TagEntity GetEntity(TagEntity entity)
        {
            if (this.Id != null) entity.Id = (long)this.Id;
            if (this.Order != null) entity.Order = this.Order;
            if (this.Name != null) entity.Name = this.Name;
            if (this.Type != null) entity.Type = this.Type;
            if (this.Offset != null) entity.Offset = this.Offset;
            if (this.DataBlockId != null) entity.DataBlockId = this.DataBlockId;
            if (this.ListDataBlock != null)
            {
                entity.DBEnityID = this.ListDataBlock;
            }
        
            return entity;
        }

        public override Dictionary<string, (string, IFormFile)> GetFiles()
        {
            Dictionary<string, (string, IFormFile)> dicRS = new Dictionary<string, (string, IFormFile)>();
            
            
            return dicRS;
        }
    }
}
