// -----------------------------------------------------------------------------
// This file was automatically generated.
// Please do not edit this file manually.
//
// Generated Date: 
//
// -----------------------------------------------------------------------------

using iSoft.DBLibrary.DBConnections.Factory;
using iSoft.Common.Enums.DBProvider;
using Serilog;
using iSoft.Common.ConfigsNS;
using SourceBaseBE.Database.Repository;
using SourceBaseBE.Database.DBContexts;
using MathNet.Numerics.Statistics.Mcmc;
using System;
using iSoft.Common.Exceptions;
using System.Data;
using Microsoft.EntityFrameworkCore.Storage;
using iSoft.Common.Models.RequestModels;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using iSoft.Database.Entities;
using System.Linq;
using SourceBaseBE.MainService.Models;
using SourceBaseBE.Database.Enums;
using iSoft.Database.Extensions;
using iSoft.Common.Models;
using SourceBaseBE.Database.Entities;
using static iSoft.Common.ConstCommon;
using iSoft.Common;
using iSoft.Common.Enums;
using iSoft.Database.Models;
using UserEntity = SourceBaseBE.Database.Entities.UserEntity;
using ISoftProjectEntity = SourceBaseBE.Database.Entities.ISoftProjectEntity;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using iSoft.Common.Utils;
using iSoft.ExportLibrary.Models;
using iSoft.ExportLibrary.Services;
using SourceBaseBE.Database.Models.RequestModels;
using SourceBaseBE.Database.Models.ResponseModels;
using System.IO.Compression;
using System.IO;
using iSoft.Common.Models.ResponseModels;
using NPOI.POIFS.FileSystem;
using System.Reflection;
using NPOI.SS.Formula.Functions;
using iSoft.Common.Models.ResponseModel;
using Nest;

namespace SourceBaseBE.MainService.Services
{
    public class BaseExample003Service : BaseCRUDService<Example003Entity>
    {
        protected UserRepository _userRepository;
        protected BaseExample003Repository _repositoryBase;
        protected Example001Repository _example001Repository;
        

        public BaseExample003Service()
        {
        }
        public BaseExample003Service(CommonDBContext dbContext, ILogger<BaseExample003Service> logger)
        {
            _dbContext = dbContext;
            _logger = logger;
            _repositoryCRUD = new BaseExample003Repository(_dbContext);
            _repositoryBase = (BaseExample003Repository)_repositoryCRUD;
            _userRepository = new UserRepository(_dbContext);
            this._example001Repository = new Example001Repository(this._dbContext);
            
        }
        public override Example003Entity GetById(long id, bool isTracking = false)
        {
            var entity = _repositoryBase.GetById(id, isTracking);
            var entityRS = (Example003Entity)_userRepository.FillTrackingUser(entity);
            return entityRS;
        }
        public override List<Example003Entity> GetList(PagingRequestModel pagingReq = null, bool isDirect = false, bool isTracking = false)
        {
            var list = _repositoryBase.GetList(pagingReq, isDirect, isTracking);
            var listRS = _userRepository.FillTrackingUser(list.Cast<BaseCRUDEntity>().ToList()).Cast<Example003Entity>().ToList();
            return listRS;
        }
        public PagingWithColumnsResponseModel GetListFilter(
            PagingFilterRequestModel request,
            bool isDirect = false,
            bool isTracking = false)
        {
            var (list0, totalRecord) = _repositoryBase.GetListFilter(request, isDirect, isTracking);
            var list = _userRepository.FillTrackingUser(list0.Cast<BaseCRUDEntity>().ToList()).Cast<Example003Entity>().ToList();

            PagingWithColumnsResponseModel rs = new PagingWithColumnsResponseModel();
            List<BaseExample003ResponseModel> listItemResponse = new BaseExample003ResponseModel().SetData(list).Cast<BaseExample003ResponseModel>().ToList();
            
            rs.ListData = listItemResponse.Cast<object>().ToList();
            rs.TotalRecord = totalRecord;
            rs.Columns = new BaseExample003ResponseModel().GetColumnAttribute();

            return rs;
        }
        public string ExportData(PagingFilterRequestModel request)
        {
            var templatePath = ConstMain.ConstTemplateExportDefault;
            string reportTemplateSheet = "sheet1";
            string excelFileNameTemplate = $"Report_{DateTime.Now.ToString(ConstDateTimeFormat.YYYYMMDD_HHMMSS_MIN)}.xlsx";
            string zipFileName = $"Report_{DateTime.Now.ToString(ConstDateTimeFormat.YYYYMMDD_HHMMSS_MIN)}.zip";
            using (var outStream = new MemoryStream())
            {
                using (var archive = new ZipArchive(outStream, ZipArchiveMode.Create, true))
                {
                    var excelFileName = string.Format(excelFileNameTemplate, request.DateFrom?.ToString("yyyyMMdd"), request.DateTo?.ToString("yyyyMMdd"));
                    var excelFilePath = $"./{excelFileName}";
                    bool isTemplateExist = File.Exists(templatePath);

                    _logger.LogInformation($"Template Path: {templatePath}");
                    _logger.LogInformation($"Template Path Exist: {isTemplateExist}");

                    ExcelPro._templatePath = templatePath;
                    using (var report = ExcelPro.LoadReportFormat())
                    {
                        var (list0, totalRecord) = _repositoryBase.GetListFilter(request, false, false);
                        var list = _userRepository.FillTrackingUser(list0.Cast<BaseCRUDEntity>().ToList()).Cast<Example003Entity>().ToList();
                        var listResponseModel = new BaseExample003ResponseModel().SetData(list).Cast<BaseExample003ResponseModel>().ToList();

                        var sheet1 = report.Workbook.Worksheets[reportTemplateSheet];
                        int rowCount = listResponseModel.Count;
                        int beginRowIndex = 2;
                        int insertEmptyRow = rowCount - 1;
                        double rowHeight = sheet1.Rows[beginRowIndex + 1].Height;

                        /************************************************************************/
                        /*                          INSERT EMPTY ROWS START                     */
                        /************************************************************************/
                        if (insertEmptyRow >= 1)
                        {
                            sheet1.InsertRow(beginRowIndex + 1, insertEmptyRow, beginRowIndex);
                            for (int i = 0; i < insertEmptyRow; i++)
                            {
                                sheet1.Rows[beginRowIndex + 1 + i].Height = rowHeight;
                            }
                        }
                        /*INSERT EMPTY ROWS END*/

                        /************************************************************************/
                        /*                          GET DATA TO listData START                  */
                        /************************************************************************/
                        int count = 0;

                        List<Dictionary<object, object>> listData = new List<Dictionary<object, object>>();
                        foreach (var item in listResponseModel)
                        {
                            var dic = new Dictionary<object, object>();

                            dic.Add("STT", ++count);

                            foreach (PropertyInfo property in typeof(BaseExample003ResponseModel).GetProperties().OrderBy(p => p.Name))
                            {
                                dic.Add(property.Name, property.GetValue(item));
                            }
                            listData.Add(dic);
                        }
                        /*GET DATA TO listData END*/

                        ExportSheetDataModel exportSheetDataModel = new ExportSheetDataModel();
                        exportSheetDataModel.SheetIndex = sheet1.Index;

                        /************************************************************************/
                        /*                          SET METADATA START                  */
                        /************************************************************************/
                        /*SET METADATA END*/

                        /************************************************************************/
                        /*                          SET DATA TO EXCEL START                  */
                        /************************************************************************/
                        exportSheetDataModel.BeginRowIndex = beginRowIndex;
                        exportSheetDataModel.BeginNoNumber = 1;
                        exportSheetDataModel.ListChartDataModel = listData;
                        int columnIndex = 0;

                        // Set header to excel
                        exportSheetDataModel.DicColumnIndex2EnvKey.Add(columnIndex++, "STT");
                        foreach (PropertyInfo property in typeof(BaseExample003ResponseModel).GetProperties().OrderBy(p => p.Name))
                        {
                            exportSheetDataModel.DicColumnIndex2EnvKey.Add(columnIndex++, property.Name);
                        }

                        string beginHeaderCellName = "A1";
                        string headerCellName = beginHeaderCellName;

                        exportSheetDataModel.DicCellName2Value.Add(headerCellName, "STT");
                        headerCellName = ConvertUtil.GetCellNext(headerCellName, Direct.Right, 1);

                        foreach (PropertyInfo property in typeof(BaseExample003ResponseModel).GetProperties().OrderBy(p => p.Name))
                        {
                            if (!exportSheetDataModel.DicCellName2Value.ContainsKey(headerCellName))
                            {
                                exportSheetDataModel.DicCellName2Value.Add(headerCellName, property.Name);
                                headerCellName = ConvertUtil.GetCellNext(headerCellName, Direct.Right, 1);
                            }
                        }

                        columnIndex++;
                        long insertedRowCount = ExportExcelService.SetFormatExcelHistory(
                              report.Workbook.Worksheets,
                              exportSheetDataModel);
                        /*SET DATA TO EXCEL END*/

                        var file = new FileInfo(excelFilePath);
                        report.SaveAs(file);
                        report.Dispose();
                        var fileInArchive = archive.CreateEntry(excelFileName, System.IO.Compression.CompressionLevel.Optimal);
                        using (var entryStream = fileInArchive.Open())
                        {
                            using (var fileInCompression = new MemoryStream(File.ReadAllBytes(excelFilePath)))
                            {
                                fileInCompression.CopyToAsync(entryStream);
                            }
                        }
                    }
                    return excelFilePath;
                }
            }
        }
        public override List<Example003Entity> GetAll()
        {
            var list = _repositoryBase.GetAll();
            var listRS = _userRepository.FillTrackingUser(list.Cast<BaseCRUDEntity>().ToList()).Cast<Example003Entity>().ToList();
            return listRS;
        }
        public override List<Dictionary<string, object>> GetFormDataObjElement(Example003Entity entity)
        {
            string entityName = nameof(Example003Entity);
            var listRS = new List<Dictionary<string, object>>();
            List<object> objectList = null;
            var properties = typeof(Example003Entity).GetProperties();
            bool addedFlag = false;
            foreach (var property in properties)
            {
                if (property.Name == nameof(BaseCRUDEntity.CreatedAt)
                    || property.Name == nameof(BaseCRUDEntity.CreatedBy)
                    || property.Name == nameof(BaseCRUDEntity.UpdatedAt)
                    || property.Name == nameof(BaseCRUDEntity.UpdatedBy)
                    || property.Name == nameof(BaseCRUDEntity.CreatedUsername)
                    || property.Name == nameof(BaseCRUDEntity.UpdatedUsername)
                    || property.Name == nameof(BaseCRUDEntity.DeletedFlag)
                    || property.Name == nameof(BaseCRUDEntity.Order))
                {
                    continue;
                }

                if (false
                    
                    )
                {
                    continue;
                }


                addedFlag = false;
                // foreignKeyAttribute
                var foreignKeyAttribute = (ForeignKeyAttribute)Attribute.GetCustomAttribute(property, typeof(ForeignKeyAttribute));
                if (foreignKeyAttribute != null && !addedFlag)
                {
                    string parentEntity = foreignKeyAttribute.Name;
                    listRS.Add(new Dictionary<string, object> {
                        {"DisplayName", GetDisplayName(property.Name, entityName)},
                        {"Key", property.Name},
                        {"Value", property.GetValue(entity)},
                        {"Type", EnumFormDataType.Select.ToStringValue().LowerFirstLetter()},
                        {"Options", GetListOptionData(parentEntity, entityName)},
                        {"IsReadonly", false},
                        {"Searchable", true},
                        {"Required", false},
                    });
                    addedFlag = true;
                }

                // ListEntityAttribute
                var listEntityAttribute = (ListEntityAttribute)Attribute.GetCustomAttribute(property, typeof(ListEntityAttribute));
                if (listEntityAttribute != null && !addedFlag)
                {
                    string childEntity = listEntityAttribute.EntityTargetName;

                    listRS.Add(new Dictionary<string, object> {
                        {"DisplayName", GetDisplayName(property.Name, entityName)},
                        {"Key", property.Name},
                        {"Value", GetListIdChildren(entity, childEntity)},
                        {"Type", listEntityAttribute.TypeName.ToStringValue().LowerFirstLetter()},
                        {"Options", GetListOptionData(childEntity, entityName, listEntityAttribute.Category)},
                        {"IsReadonly", false},
                        {"Searchable", true},
                        {"Required", false},
                    });
                    addedFlag = true;
                }

                // ListEntityAttribute
                var formDataTypeAttr = (FormDataTypeAttribute)Attribute.GetCustomAttribute(property, typeof(FormDataTypeAttribute));

                if (formDataTypeAttr == null && !addedFlag)
                {
                    if (property.PropertyType == typeof(string) || Nullable.GetUnderlyingType(property.PropertyType) == typeof(string))
                    {
                        formDataTypeAttr = new FormDataTypeAttributeText(EnumFormDataType.Textbox);
                    }
                    else if (property.PropertyType == typeof(DateTime) || Nullable.GetUnderlyingType(property.PropertyType) == typeof(DateTime))
                    {
                        formDataTypeAttr = new FormDataTypeAttributeDatetime(EnumFormDataType.Datetime);
                    }
                    else if (property.PropertyType == typeof(int) || Nullable.GetUnderlyingType(property.PropertyType) == typeof(int)
                      || property.PropertyType == typeof(long) || Nullable.GetUnderlyingType(property.PropertyType) == typeof(long)
                      || property.PropertyType == typeof(short) || Nullable.GetUnderlyingType(property.PropertyType) == typeof(short))
                    {
                        formDataTypeAttr = new FormDataTypeAttributeNumber(EnumFormDataType.IntegerNumber);
                    }
                    else if (property.PropertyType == typeof(float) || Nullable.GetUnderlyingType(property.PropertyType) == typeof(float)
                        || property.PropertyType == typeof(double) || Nullable.GetUnderlyingType(property.PropertyType) == typeof(double))
                    {
                        formDataTypeAttr = new FormDataTypeAttributeNumber(EnumFormDataType.FloatNumber);
                    }
                    else if (property.PropertyType == typeof(bool) || Nullable.GetUnderlyingType(property.PropertyType) == typeof(bool))
                    {
                        formDataTypeAttr = new FormDataTypeAttributeSelect(EnumFormDataType.Checkbox, new object[] { true, false });
                    }
                    else if (property.PropertyType.IsEnum)
                    {
                        var arrEnum = Enum.GetValues<EnumPermissionTable>();

                        listRS.Add(new Dictionary<string, object> {
                                    {"DisplayName", GetDisplayName(property.Name, entityName)},
                                    {"Key", property.Name},
                                    {"Value", property.GetValue(entity)},
                                    {"Type", EnumFormDataType.Select.ToStringValue().LowerFirstLetter()},
                                    {"Options", arrEnum.Select(x => new FormSelectOptionModel((int)x, x.ToString())).Cast<object>().ToList()},
                                    {"IsReadonly", false},
                                    {"Searchable", true},
                                    {"Required", false},
                        });
                        addedFlag = true;
                    }
                    else if (property.PropertyType.IsAssignableFrom(typeof(BaseCRUDEntity)) || typeof(BaseCRUDEntity).IsAssignableFrom(property.PropertyType))
                    {
                        // Do nothing
                    }
                    else
                    {
                        //throw new NotImplementedException($"Unknown property: {property.PropertyType}");
                    }
                }

                if (formDataTypeAttr != null && !addedFlag)
                {
                    if (formDataTypeAttr.Options != null)
                    {
                        objectList = new List<object>(formDataTypeAttr.Options);
                    }
                    string value = "";
                    switch (formDataTypeAttr.TypeName)
                    {
                        case EnumFormDataType.IntegerNumber:
                        case EnumFormDataType.FloatNumber:
                            listRS.Add(new Dictionary<string, object> {
                                {"DisplayName", GetDisplayName(property.Name, entityName)},
                                {"Key", property.Name},
                                {"Value", property.GetValue(entity)},
                                {"Type", formDataTypeAttr.TypeName.ToStringValue().LowerFirstLetter()},
                                {"Min", formDataTypeAttr.Min},
                                {"Max", formDataTypeAttr.Max},
                                {"DefaultValue", formDataTypeAttr.DefaultVal},
                                {"Unit", formDataTypeAttr.Unit},
                                {"IsReadonly", formDataTypeAttr.IsReadonly},
                                {"ValidationRules", formDataTypeAttr.ValidationRules},
                                {"Required", formDataTypeAttr.IsRequired },
                            });
                            addedFlag = true;
                            break;
                        case EnumFormDataType.Textbox:
                        case EnumFormDataType.Textarea:
                        case EnumFormDataType.Email:
                        case EnumFormDataType.PhoneNumber:
                            listRS.Add(new Dictionary<string, object> {
                                {"DisplayName", GetDisplayName(property.Name, entityName)},
                                {"Key", property.Name},
                                {"Value", property.GetValue(entity)},
                                {"Type", formDataTypeAttr.TypeName.ToStringValue().LowerFirstLetter()},
                                {"PlaceHolder", formDataTypeAttr.Placeholder},
                                {"MaxRow", formDataTypeAttr.MaxRow},
                                {"MaxLen", formDataTypeAttr.MaxLen},
                                {"Unit", formDataTypeAttr.Unit},
                                {"IsReadonly", formDataTypeAttr.IsReadonly},
                                {"ValidationRules", formDataTypeAttr.ValidationRules},
                                {"Required", formDataTypeAttr.IsRequired },
                            });
                            addedFlag = true;
                            break;
                        case EnumFormDataType.Password:
                            listRS.Add(new Dictionary<string, object> {
                                {"DisplayName", GetDisplayName(property.Name, entityName)},
                                {"Key", property.Name},
                                {"Value", property.GetValue(entity) == null ? null : new string('*', property.GetValue(entity).ToString().Length)},
                                {"Type", formDataTypeAttr.TypeName.ToStringValue().LowerFirstLetter()},
                                {"PlaceHolder", formDataTypeAttr.Placeholder},
                                {"MaxRow", formDataTypeAttr.MaxRow},
                                {"MaxLen", formDataTypeAttr.MaxLen},
                                {"Unit", formDataTypeAttr.Unit},
                                {"IsReadonly", formDataTypeAttr.IsReadonly},
                                {"ValidationRules", formDataTypeAttr.ValidationRules},
                                {"Required", formDataTypeAttr.IsRequired },
                            });
                            addedFlag = true;
                            break;
                        case EnumFormDataType.Label:
                        case EnumFormDataType.Hidden:
                            listRS.Add(new Dictionary<string, object> {
                                {"DisplayName", GetDisplayName(property.Name, entityName)},
                                {"Key", property.Name},
                                {"Value", property.GetValue(entity)},
                                {"Type", formDataTypeAttr.TypeName.ToStringValue().LowerFirstLetter()},
                                {"Unit", formDataTypeAttr.Unit},
                                {"IsReadonly", formDataTypeAttr.IsReadonly},
                                {"Required", formDataTypeAttr.IsRequired },
                            });
                            addedFlag = true;
                            break;
                        case EnumFormDataType.Datetime:
                            listRS.Add(new Dictionary<string, object> {
                                {"DisplayName", GetDisplayName(property.Name, entityName)},
                                {"Key", property.Name},
                                {"Value", property.GetValue(entity)},
                                {"Type", formDataTypeAttr.TypeName.ToStringValue().LowerFirstLetter()},
                                {"Min", formDataTypeAttr.Min},
                                {"Max", formDataTypeAttr.Max},
                                {"DefaultValue", formDataTypeAttr.DefaultVal},
                                {"IsReadonly", formDataTypeAttr.IsReadonly},
                                {"Required", formDataTypeAttr.IsRequired },
                            });
                            addedFlag = true;
                            break;
                        case EnumFormDataType.DateOnly:
                            value = property.GetValue(entity) == null ? "" : ((DateTime)property.GetValue(entity)).ToString(ConstDateTimeFormat.YYYYMMDD);
                            listRS.Add(new Dictionary<string, object> {
                                {"DisplayName", GetDisplayName(property.Name, entityName)},
                                {"Key", property.Name},
                                {"Value",value },
                                {"Type", formDataTypeAttr.TypeName.ToStringValue().LowerFirstLetter()},
                                {"Min", formDataTypeAttr.Min},
                                {"Max", formDataTypeAttr.Max},
                                {"DefaultValue", formDataTypeAttr.DefaultVal},
                                {"IsReadonly", formDataTypeAttr.IsReadonly},
                                {"Required", formDataTypeAttr.IsRequired },
                            });
                            addedFlag = true;
                            break;
                        case EnumFormDataType.TimeOnly:
                            value = property.GetValue(entity) == null ? "" : ((DateTime)property.GetValue(entity)).ToString(ConstDateTimeFormat.HHMMSS);
                            listRS.Add(new Dictionary<string, object> {
                                {"DisplayName", GetDisplayName(property.Name, entityName)},
                                {"Key", property.Name},
                                {"Value",value },
                                {"Type", formDataTypeAttr.TypeName.ToStringValue().LowerFirstLetter()},
                                {"Min", formDataTypeAttr.Min},
                                {"Max", formDataTypeAttr.Max},
                                {"DefaultValue", formDataTypeAttr.DefaultVal},
                                {"IsReadonly", formDataTypeAttr.IsReadonly},
                                {"Required", formDataTypeAttr.IsRequired },
                            });
                            addedFlag = true;
                            break;
                        case EnumFormDataType.Radio:
                            listRS.Add(new Dictionary<string, object> {
                                {"DisplayName", GetDisplayName(property.Name, entityName)},
                                {"Key", property.Name},
                                {"Value", property.GetValue(entity)},
                                {"Type", formDataTypeAttr.TypeName.ToStringValue().LowerFirstLetter()},
                                {"Options", GetListOptionData(objectList)},
                                {"DefaultValue", formDataTypeAttr.DefaultVal},
                                {"Unit", formDataTypeAttr.Unit},
                                {"IsReadonly", formDataTypeAttr.IsReadonly},
                                {"Required", formDataTypeAttr.IsRequired },
                            });
                            addedFlag = true;
                            break;
                        case EnumFormDataType.Checkbox:
                            listRS.Add(new Dictionary<string, object> {
                                {"DisplayName", GetDisplayName(property.Name, entityName)},
                                {"Key", property.Name},
                                {"Value", property.GetValue(entity)},
                                {"Type", formDataTypeAttr.TypeName.ToStringValue().LowerFirstLetter()},
                                {"Options", null},
                                {"DefaultValue", formDataTypeAttr.DefaultVal},
                                {"Unit", formDataTypeAttr.Unit},
                                {"IsReadonly", formDataTypeAttr.IsReadonly},
                                {"Required", formDataTypeAttr.IsRequired },
                            });
                            addedFlag = true;
                            break;
                        case EnumFormDataType.CheckboxMulti:
                            listRS.Add(new Dictionary<string, object> {
                                {"DisplayName", GetDisplayName(property.Name, entityName)},
                                {"Key", property.Name},
                                {"Value", GetListValueData(property.GetValue(entity)?.ToString())},
                                {"Type", formDataTypeAttr.TypeName.ToStringValue().LowerFirstLetter()},
                                {"Options", GetListOptionData(objectList)},
                                {"DefaultValue", formDataTypeAttr.DefaultVal},
                                {"Unit", formDataTypeAttr.Unit},
                                {"IsReadonly", formDataTypeAttr.IsReadonly},
                                {"Required", formDataTypeAttr.IsRequired },
                            });
                            addedFlag = true;
                            break;
                        case EnumFormDataType.Select:
                            listRS.Add(new Dictionary<string, object> {
                                {"DisplayName", GetDisplayName(property.Name, entityName)},
                                {"Key", property.Name},
                                {"Value", property.GetValue(entity)},
                                {"Type", formDataTypeAttr.TypeName.ToStringValue().LowerFirstLetter()},
                                {"Options", GetListOptionData(objectList)},
                                {"Searchable", formDataTypeAttr.Searchable},
                                {"DefaultValue", formDataTypeAttr.DefaultVal},
                                {"IsReadonly", formDataTypeAttr.IsReadonly},
                                {"Required", formDataTypeAttr.IsRequired },
                            });
                            addedFlag = true;
                            break;
                        case EnumFormDataType.SelectMulti:
                            listRS.Add(new Dictionary<string, object> {
                                {"DisplayName", GetDisplayName(property.Name, entityName)},
                                {"Key", property.Name},
                                {"Value", GetListValueData(property.GetValue(entity)?.ToString())},
                                {"Type", formDataTypeAttr.TypeName.ToStringValue().LowerFirstLetter()},
                                {"Options", GetListOptionData(objectList)},
                                {"Searchable", formDataTypeAttr.Searchable},
                                {"DefaultValue", formDataTypeAttr.DefaultVal},
                                {"IsReadonly", formDataTypeAttr.IsReadonly},
                                {"Required", formDataTypeAttr.IsRequired },
                            });
                            addedFlag = true;
                            break;
                        case EnumFormDataType.Timespan:
                            listRS.Add(new Dictionary<string, object> {
                                {"DisplayName", GetDisplayName(property.Name, entityName)},
                                {"Key", property.Name},
                                {"Value", property.GetValue(entity)},
                                {"Type", formDataTypeAttr.TypeName.ToStringValue().LowerFirstLetter()},
                                {"Min", formDataTypeAttr.Min},
                                {"Max", formDataTypeAttr.Max},
                                {"MinLevelDateTime", formDataTypeAttr.MinLevelDateTime?.ToString()},
                                {"MaxLevelDateTime", formDataTypeAttr.MaxLevelDateTime?.ToString()},
                                {"DefaultValue", formDataTypeAttr.DefaultVal},
                                {"IsReadonly", formDataTypeAttr.IsReadonly},
                                {"Required", formDataTypeAttr.IsRequired },
                            });
                            addedFlag = true;
                            break;
                        case EnumFormDataType.Image:
                            listRS.Add(new Dictionary<string, object> {
                                {"DisplayName", GetDisplayName(property.Name, entityName)},
                                {"Key", property.Name},
                                {"Value", property.GetValue(entity)},
                                {"Type", formDataTypeAttr.TypeName.ToStringValue().LowerFirstLetter()},
                                {"Width", formDataTypeAttr.Width},
                                {"Height", formDataTypeAttr.Height},
                                {"MaxFileSizeInMB", formDataTypeAttr.MaxFileSizeInMB},
                                {"FileExtension", formDataTypeAttr.FileExtension},
                                {"IsReadonly", formDataTypeAttr.IsReadonly},
                                {"Required", formDataTypeAttr.IsRequired },
                            });
                            addedFlag = true;
                            break;
                        case EnumFormDataType.ListImage:
                            listRS.Add(new Dictionary<string, object> {
                                {"DisplayName", GetDisplayName(property.Name, entityName)},
                                {"Key", property.Name},
                                {"Value", GetListValueData(property.GetValue(entity)?.ToString())},
                                {"Type", formDataTypeAttr.TypeName.ToStringValue().LowerFirstLetter()},
                                {"MaxFileSizeInMB", formDataTypeAttr.MaxFileSizeInMB},
                                {"FileExtension", formDataTypeAttr.FileExtension},
                                {"IsReadonly", formDataTypeAttr.IsReadonly},
                                {"Required", formDataTypeAttr.IsRequired },
                            });
                            addedFlag = true;
                            break;
                        case EnumFormDataType.File:
                            listRS.Add(new Dictionary<string, object> {
                                {"DisplayName", GetDisplayName(property.Name, entityName)},
                                {"Key", property.Name},
                                {"Value", property.GetValue(entity)},
                                {"Type", formDataTypeAttr.TypeName.ToStringValue().LowerFirstLetter()},
                                {"MaxFileSizeInMB", formDataTypeAttr.MaxFileSizeInMB},
                                {"FileExtension", formDataTypeAttr.FileExtension},
                                {"IsReadonly", formDataTypeAttr.IsReadonly},
                                {"Required", formDataTypeAttr.IsRequired },
                            });
                            addedFlag = true;
                            break;
                        case EnumFormDataType.ListFile:
                            listRS.Add(new Dictionary<string, object> {
                                {"DisplayName", GetDisplayName(property.Name, entityName)},
                                {"Key", property.Name},
                                {"Value", GetListValueData(property.GetValue(entity)?.ToString())},
                                {"Type", formDataTypeAttr.TypeName.ToStringValue().LowerFirstLetter()},
                                {"MaxFileSizeInMB", formDataTypeAttr.MaxFileSizeInMB},
                                {"FileExtension", formDataTypeAttr.FileExtension},
                                {"IsReadonly", formDataTypeAttr.IsReadonly},
                                {"Required", formDataTypeAttr.IsRequired },
                            });
                            addedFlag = true;
                            break;
                        default:
                            //listRS.Add(new Dictionary<string, object> {
                            //    {"DisplayName", GetDisplayName(property.Name, entityName)},
                            //    {"Key", property.Name},
                            //    {"Value", property.GetValue(item)},
                            //    {"Type", formDataTypeAttr.TypeName.ToStringValue().LowerFirstLetter()},
                            //    {"IsReadonly", formDataTypeAttr.IsReadonly},
                            //});
                            //addedFlag = true;
                            throw new NotImplementedException($"EnumFormDataType not found, {formDataTypeAttr.TypeName.ToString()}");
                            break;
                    }
                }
            }
            return listRS;
        }

        /// <summary>
        /// UpsertIfNotExist (@GenCRUD)
        /// </summary>
        /// <param name="entity"></param>
        /// <param name="userId"></param>
        /// <returns></returns>
        public override Example003Entity Upsert(Example003Entity entity, long? userId = null)
        {
            List<Example001Entity> example001Children = null;
            if (entity.Example001Ids != null && entity.Example001Ids.Count >= 1)
            {
                example001Children = _example001Repository.GetListByListIds(entity.Example001Ids, true, true);
                if (example001Children == null || example001Children.Count <= 0)
                {
                    throw new DBException($"example001Children not found, ids: {string.Join(",", entity.Example001Ids)}");
                }
            }
            
            ((BaseExample003Repository)_repositoryBase).Upsert(entity, example001Children, userId);

            var upsertedEntity = ((BaseExample003Repository)_repositoryBase).GetById(entity.Id, false);

            var entityRS = (Example003Entity)_userRepository.FillTrackingUser(upsertedEntity);
            return entityRS;
        }
        public override int Delete(long id, long? userId = null, bool isSoftDelete = true)
        {
            int deletedCount = _repositoryBase.Delete(id, userId, isSoftDelete);
            return deletedCount;
        }

        /// <summary>
        /// GetListIdChildren (@GenCRUD)
        /// </summary>
        /// <param name="entity"></param>
        /// <param name="childEntity"></param>
        /// <returns></returns>
        public List<long> GetListIdChildren(Example003Entity entity, string childEntity)
        {
            switch (childEntity)
            {

                case nameof(Example001Entity):
                    if (entity.ListExample001 == null)
                    {
                        return new List<long>();
                    }
                    return entity.ListExample001.Select(x => x.Id).ToList();
                
                default:
                    return new List<long>();
            }
        }

        /// <summary>
        /// GetListOptionData (@GenCRUD)
        /// </summary>
        /// <param name="targetEntity"></param>
        /// <param name="entityName"></param>
        /// <param name="category"></param>
        /// <returns></returns>
        public List<FormSelectOptionModel> GetListOptionData(string targetEntity, string entityName, EnumAttributeRelationshipType category = EnumAttributeRelationshipType.Many2Many)
        {
            var listRS = new List<FormSelectOptionModel>();
            switch (targetEntity)
            {
                case nameof(Example001Entity):
                        listRS = this._example001Repository.GetSelectData(entityName, category);
                        break;
                
                default:
                    break;
            }
            return listRS;
        }

        public override Example003Entity SetFileURL(Example003Entity entity, Dictionary<string, string> dicImagePath)
        {
            if (dicImagePath != null && dicImagePath.Count >= 1)
            {
                
            }
            return entity;
        }

        //public Example003Entity UpsertTestTransaction(Example003Entity item, long? userId = null)
        //{
        //  using (var transaction = this._dbContext.Database.BeginTransaction())
        //  {
        //    try
        //    {
        //      _repositoryBase...
        //      _userRepository...
        //      transaction.Commit();
        //    }
        //    catch (Exception ex)
        //    {
        //      try
        //      {
        //        transaction.Rollback();
        //      }
        //      catch { }
        //      throw new DBException(ex);
        //    }
        //  }
        //}
    }
}