version: "3"

networks:
  drmt-net:
    external: true
  db-net:
    external: true
  cache-net:
    external: true
  broker-net:
    external: true
  search-net:
    external: true

volumes:
  drmt-mms-main-wwwroot:
  
services:

  drmt-mms-main:
    image: drmt-mms-main:staging
    container_name: drmt-mms-main
    restart: always
    build:
      context: ./../
      dockerfile: src/DRMT.MMS.Main/Dockerfile
    networks:
      - drmt-net
      - db-net
      - broker-net
      - search-net
      - cache-net
    labels:
      org.label-schema.group: "monitoring"
    ports:
      - 2802:80
      - 12802:443
    environment:
      - TZ=Asia/Ho_Chi_Minh

      - ENV=${ENV}

      - VERSION=${VERSION}
      - AUTHENTICATION_SECRET=${AUTHENTICATION_SECRET}
      - ENCRYPT_HANDSHAKE_SECRET_KEY=${ENCRYPT_HANDSHAKE_SECRET_KEY}
      - LIST_ACCEPTED_API_KEY=${LIST_ACCEPTED_API_KEY}
      - API_KEY=${API_KEY}

      - MASTER_DB_CONFIG__DATABASE_TYPE=${MASTER_DB_CONFIG__DATABASE_TYPE}
      - MASTER_DB_CONFIG__ADDRESS=${MASTER_DB_CONFIG__ADDRESS}
      - MASTER_DB_CONFIG__PORT=${MASTER_DB_CONFIG__PORT}
      - MASTER_DB_CONFIG__DATABASE_NAME=${MASTER_DB_CONFIG__DATABASE_NAME}
      - MASTER_DB_CONFIG__USERNAME=${MASTER_DB_CONFIG__USERNAME}
      - MASTER_DB_CONFIG__PASSWORD=${MASTER_DB_CONFIG__PASSWORD}

      - RABBITMQ_CONFIG__ADDRESS=${RABBITMQ_CONFIG__ADDRESS}
      - RABBITMQ_CONFIG__PORT=${RABBITMQ_CONFIG__PORT}
      - RABBITMQ_CONFIG__USERNAME=${RABBITMQ_CONFIG__USERNAME}
      - RABBITMQ_CONFIG__PASSWORD=${RABBITMQ_CONFIG__PASSWORD}

      - ELASTICSEARCH_CONFIG__ADDRESS=${ELASTICSEARCH_CONFIG__ADDRESS}
      - ELASTICSEARCH_CONFIG__PORT=${ELASTICSEARCH_CONFIG__PORT}
      - ELASTICSEARCH_CONFIG__USERNAME=${ELASTICSEARCH_CONFIG__USERNAME}
      - ELASTICSEARCH_CONFIG__PASSWORD=${ELASTICSEARCH_CONFIG__PASSWORD}

      - REDIS_CONFIG__ADDRESS=${REDIS_CONFIG__ADDRESS}
      - REDIS_CONFIG__PORT=${REDIS_CONFIG__PORT}
      - REDIS_CONFIG__USERNAME=${REDIS_CONFIG__USERNAME}
      - REDIS_CONFIG__PASSWORD=${REDIS_CONFIG__PASSWORD}

      - REDIS_SUPPORT_CONFIG__ADDRESS=${REDIS_SUPPORT_CONFIG__ADDRESS}
      - REDIS_SUPPORT_CONFIG__PORT=${REDIS_SUPPORT_CONFIG__PORT}
      - REDIS_SUPPORT_CONFIG__USERNAME=${REDIS_SUPPORT_CONFIG__USERNAME}
      - REDIS_SUPPORT_CONFIG__PASSWORD=${REDIS_SUPPORT_CONFIG__PASSWORD}

      - SOCKETIO_CONFIG__ADDRESS=${SOCKETIO_CONFIG__ADDRESS}
      - SOCKETIO_CONFIG__PORT=${SOCKETIO_CONFIG__PORT}
      - SOCKETIO_CONFIG__REALTIME_DATA_QUEUE=${SOCKETIO_CONFIG__REALTIME_DATA_QUEUE}
      - SOCKETIO_CONFIG__CHECK_RABBIT_CONNECTION_INTERVAL=${SOCKETIO_CONFIG__CHECK_RABBIT_CONNECTION_INTERVAL}
      - SOCKETIO_CONFIG__REALTIME_DATA_ROOM=${SOCKETIO_CONFIG__REALTIME_DATA_ROOM}
      - SOCKETIO_CONFIG__REALTIME_DATA_CHANNEL=${SOCKETIO_CONFIG__REALTIME_DATA_CHANNEL}

      - CONNECTIVITY__ADDRESS=${CONNECTIVITY__ADDRESS}
      - CONNECTIVITY__PORT=${CONNECTIVITY__PORT}
      - CONNECTIVITY__API_KEY=${CONNECTIVITY__API_KEY}
      
      - AUTH__ADDRESS=${AUTH__ADDRESS}
      - AUTH__PORT=${AUTH__PORT}

    volumes:
      - "drmt-mms-main-wwwroot:/app/wwwroot"
    deploy:
      resources:
        limits:
          memory: 2600M
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
