// -----------------------------------------------------------------------------
// This file was automatically generated.
// Please do not edit this file manually.
//
// Generated Date: 
//
// -----------------------------------------------------------------------------

using iSoft.Common.Utils;
using Microsoft.AspNetCore.Http;
using SourceBaseBE.Database.Entities;
using static iSoft.Common.ConstCommon;
using iSoft.Common.Enums;
using SourceBaseBE.Database.Enums;
using iSoft.Common;

namespace SourceBaseBE.Database.Models.RequestModels
{
    public class BaseLineRequestModel : BaseCRUDRequestModel<LineEntity>
    {
        public virtual string Name { get; set; }
        public virtual List<long>? ListOeePoint { get; set; }
        public virtual List<long>? ListMachine { get; set; }
        public virtual List<long>? ListBreakTime { get; set; }
        public virtual List<long>? ListShift { get; set; }
        public virtual long? WorkshopId { get; set; }
        
        public override LineEntity GetEntity(LineEntity entity)
        {
            if (this.Id != null) entity.Id = (long)this.Id;
            if (this.Order != null) entity.Order = this.Order;
            if (this.Name != null) entity.Name = this.Name;
            if (this.ListOeePoint != null)
            {
                entity.OeePointIds = this.ListOeePoint.Select(x => x).ToList();
            }
            if (this.ListMachine != null)
            {
                entity.MachineIds = this.ListMachine.Select(x => x).ToList();
            }
            if (this.ListBreakTime != null)
            {
                entity.BreakTimeIds = this.ListBreakTime.Select(x => x).ToList();
            }
            if (this.ListShift != null)
            {
                entity.ShiftIds = this.ListShift.Select(x => x).ToList();
            }
            if (this.WorkshopId != null) entity.WorkshopId = this.WorkshopId;
        
            return entity;
        }

        public override Dictionary<string, (string, IFormFile)> GetFiles()
        {
            Dictionary<string, (string, IFormFile)> dicRS = new Dictionary<string, (string, IFormFile)>();
            
            
            return dicRS;
        }
    }
}
