// -----------------------------------------------------------------------------
// This file was automatically generated.
// Please do not edit this file manually.
//
// Generated Date: 
//
// -----------------------------------------------------------------------------

using iSoft.Common.Utils;
using Microsoft.AspNetCore.Http;
using SourceBaseBE.Database.Entities;
using static iSoft.Common.ConstCommon;
using iSoft.Common.Enums;
using SourceBaseBE.Database.Enums;
using iSoft.Common;

namespace SourceBaseBE.Database.Models.RequestModels
{
    public class BasePermissionDetailRequestModel : BaseCRUDRequestModel<PermissionDetailEntity>
    {
        public virtual string PermissionTable { get; set; }
        public virtual bool? View { get; set; }
        public virtual bool? Create { get; set; }
        public virtual bool? Edit { get; set; }
        public virtual bool? Delete { get; set; }
        public virtual bool? Request { get; set; }
        public virtual bool? Approve { get; set; }
        public virtual long? PermissionId { get; set; }
        
        public override PermissionDetailEntity GetEntity(PermissionDetailEntity entity)
        {
            if (this.Id != null) entity.Id = (long)this.Id;
            if (this.Order != null) entity.Order = this.Order;
            if (this.PermissionTable != null) entity.PermissionTable = this.PermissionTable;
            if (this.View != null) entity.View = this.View;
            if (this.Create != null) entity.Create = this.Create;
            if (this.Edit != null) entity.Edit = this.Edit;
            if (this.Delete != null) entity.Delete = this.Delete;
            if (this.Request != null) entity.Request = this.Request;
            if (this.Approve != null) entity.Approve = this.Approve;
            if (this.PermissionId != null) entity.PermissionId = this.PermissionId;
        
            return entity;
        }

        public override Dictionary<string, (string, IFormFile)> GetFiles()
        {
            Dictionary<string, (string, IFormFile)> dicRS = new Dictionary<string, (string, IFormFile)>();
            
            
            return dicRS;
        }
    }
}
