// -----------------------------------------------------------------------------
// This file was automatically generated.
// Please do not edit this file manually.
//
// Generated Date: 
//
// -----------------------------------------------------------------------------

using iSoft.Common.Utils;
using Microsoft.AspNetCore.Http;
using SourceBaseBE.Database.Entities;
using static iSoft.Common.ConstCommon;
using iSoft.Common.Enums;
using SourceBaseBE.Database.Enums;
using iSoft.Common;

namespace SourceBaseBE.Database.Models.RequestModels
{
    public class BaseMachineRequestModel : BaseCRUDRequestModel<MachineEntity>
    {
        public virtual string Name { get; set; }
        public virtual List<long>? ListOeePoint { get; set; }
        public virtual long? LineId { get; set; }
        
        public override MachineEntity GetEntity(MachineEntity entity)
        {
            if (this.Id != null) entity.Id = (long)this.Id;
            if (this.Order != null) entity.Order = this.Order;
            if (this.Name != null) entity.Name = this.Name;
            if (this.ListOeePoint != null)
            {
                entity.OeePointIds = this.ListOeePoint.Select(x => x).ToList();
            }
            if (this.LineId != null) entity.LineId = this.LineId;
        
            return entity;
        }

        public override Dictionary<string, (string, IFormFile)> GetFiles()
        {
            Dictionary<string, (string, IFormFile)> dicRS = new Dictionary<string, (string, IFormFile)>();
            
            
            return dicRS;
        }
    }
}
