// -----------------------------------------------------------------------------
// This file was automatically generated.
// Please do not edit this file manually.
//
// Generated Date: 
//
// -----------------------------------------------------------------------------

using iSoft.Common.Utils;
using Microsoft.AspNetCore.Http;
using SourceBaseBE.Database.Entities;
using static iSoft.Common.ConstCommon;
using iSoft.Common.Enums;
using SourceBaseBE.Database.Enums;
using iSoft.Common;
using iSoft.Common.Models.RequestModels;

namespace SourceBaseBE.Database.Models.RequestModels
{
    public class BaseExample004RequestModel : BaseCRUDRequestModel<Example004Entity>
    {
    }
}
