// -----------------------------------------------------------------------------
// This file was automatically generated.
// Please do not edit this file manually.
//
// Generated Date: 
//
// -----------------------------------------------------------------------------

using iSoft.Common.Utils;
using Microsoft.AspNetCore.Http;
using SourceBaseBE.Database.Entities;
using static iSoft.Common.ConstCommon;
using iSoft.Common;
using iSoft.Database.Models.RequestModels.Base.BaseCRUD;
using SourceBaseBE.Database.Enums;
using iSoft.Common.Enums;
using iSoft.Database.Entities;

namespace SourceBaseBE.Database.Models.RequestModels
{
    public class BaseExample001TransRequestModel : BaseCRUDRequestModel<Example001TransEntity>
    {
        //public virtual string SerialCode { get; set; }
        public virtual string Name { get; set; }
        public virtual string? Description { get; set; }

        // Trans
        public virtual string Lang { get; set; }
        public long BaseId { get; set; }

        public override Example001TransEntity GetEntity(Example001TransEntity entity)
        {
            if (this.Id != null) entity.Id = (long)this.Id;
            if (this.Order != null) entity.Order = this.Order;
            //if (this.SerialCode != null) entity.SerialCode = this.SerialCode;
            if (this.Name != null) entity.Name = this.Name;
            if (this.Description != null) entity.Description = this.Description;

            // Trans
            if (this.Lang != null) entity.Lang = this.Lang;
            if (this.BaseId != null && this.BaseId != 0) entity.BaseId = this.BaseId;

            return entity;
        }

        public override Dictionary<string, (string, IFormFile)> GetFiles()
        {
            Dictionary<string, (string, IFormFile)> dicRS = new Dictionary<string, (string, IFormFile)>();
            
            
            return dicRS;
        }
    }
}
